feat(redocly): check bundle and run lint
hedia-team/.github pull request #38
Opened 2024-06-03 14:03 UTC by MathieuVeber

2024-06-03 14:24 UTC, Styrke requested changes

2024-06-03 14:24 UTC, Styrke commented on .github/workflows/redocly.yml
> +            - name: Is the bundle up to date?
I don't think questions are good as names for workflow steps.

How about "Check that bundle is up to date"?

2024-06-03 14:32 UTC, aimeerivers requested changes
just a small suggestion.

2024-06-03 14:32 UTC, aimeerivers commented on .github/workflows/redocly.yml
> +              uses: actions/checkout@v4
maybe add `with: fetch-depth: 1` so it doesn't clone the entire repository

2024-06-03 14:34 UTC, MathieuVeber commented on .github/workflows/redocly.yml
> +              uses: actions/checkout@v4
It's the default https://github.com/actions/checkout?tab=readme-ov-file#usage

2024-06-03 14:34 UTC, aimeerivers commented
do we have an example of a PR that runs these checks (and fails?) .. would be good to see how it looks.

2024-06-03 14:34 UTC, aimeerivers commented on .github/workflows/redocly.yml
> +              uses: actions/checkout@v4
😮

2024-06-03 14:35 UTC, MathieuVeber commented
> do we have an example of a PR that runs these checks (and fails?) .. would be good to see how it looks.

Yes in [data-service](https://github.com/hedia-team/data-service/pull/38)

Check out the failing actions 😉 https://github.com/hedia-team/data-service/actions/workflows/continuous-integration.yml

2024-06-03 15:00 UTC, aimeerivers commented on .github/workflows/redocly.yml
> +              uses: actions/checkout@v4
so it is!! i never knew!

2024-06-03 15:04 UTC, aimeerivers approved these changes
excellent! i really like your step naming too! was going to say something about imperative verbs, but i see you already fixed it! 😄

2024-06-04 06:12 UTC, aimeerivers approved these changes
just coming back to confirm, i don't require any changes.

2024-06-04 07:00 UTC, MathieuVeber commented
> just coming back to confirm, i don't require any changes.

This is not about you it's about @Styrke 😜

2024-06-04 08:45 UTC, Styrke approved these changes
Looks good. Looking forward to it. 👍

Sorry, I didn't realize the PR was waiting for me.

2024-06-04 08:45 UTC, merged